# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=60)),
                ('detail', models.CharField(default='', max_length=500)),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='UEPTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('detail', models.CharField(default='', max_length=500)),
                ('body', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
