# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('detail', models.TextField(default='', max_length=500)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('detail', models.TextField(default='', max_length=500)),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='docentes',
            name='detail',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
