# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170904_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, max_length=200, null=True, upload_to='gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='photo',
        ),
        migrations.AlterField(
            model_name='docentes',
            name='photo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='galeriaphotos',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Galeria'),
        ),
    ]
