# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 20:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170912_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='galeriaphotos',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=b''),
        ),
    ]
