# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170912_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='galeriaphotos',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='photos'),
        ),
    ]
