# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 04:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170912_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='galeriaphotos',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500),
        ),
    ]
