# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 03:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170914_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ueptemplate',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
