# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170920_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nombre_completo', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('mensaje', models.CharField(default='', max_length=2000)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
