# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
