# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20171016_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
