# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20171016_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='autor',
            field=models.CharField(default='', max_length=60),
        ),
    ]
