# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 02:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_articulos_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(default='', max_length=100, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500, verbose_name='Detalle del evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Publicar?'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='start_date',
            field=models.DateTimeField(verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='T\xedtulo del Evento'),
        ),
    ]
