# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 02:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20171018_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='email',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Corre Electr\xf3nico'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='autor',
            field=models.CharField(default='', max_length=60, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha de Publicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500, verbose_name='Detalle del Art\xedculo'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='articles', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Publicar?'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='T\xedtulo del Art\xedculo'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='detail',
            field=models.TextField(default='', max_length=500, verbose_name='Resumen del Docente'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Apellido y Nombre'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profiles', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Publicar?'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='detail',
            field=models.TextField(default='', max_length=500, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='photos', verbose_name='Foto de portada'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Publicar?'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='Nombre de la Galer\xeda'),
        ),
        migrations.AlterField(
            model_name='galeriaphotos',
            name='detail',
            field=ckeditor.fields.RichTextField(default='', max_length=500, verbose_name='Detalle de la foto'),
        ),
        migrations.AlterField(
            model_name='galeriaphotos',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='photos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ueptemplate',
            name='body',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Texto completo'),
        ),
        migrations.AlterField(
            model_name='ueptemplate',
            name='detail',
            field=models.CharField(default='', max_length=500, verbose_name='Detalle de la p\xe1gina Principal'),
        ),
        migrations.AlterField(
            model_name='ueptemplate',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo Principal'),
        ),
    ]
