# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20171018_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ueptemplate',
            name='detail_photo_1',
            field=models.CharField(default='', max_length=500, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='detail_photo_2',
            field=models.CharField(default='', max_length=500, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='detail_photo_3',
            field=models.CharField(default='', max_length=500, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='detail_photo_4',
            field=models.CharField(default='', max_length=500, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profiles', verbose_name='Primera foto de portada'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profiles', verbose_name='Segunda foto de portada'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profiles', verbose_name='Tercera foto de portada'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profiles', verbose_name='Cuarta foto de portada'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_articles',
            field=models.CharField(default='', max_length=700, verbose_name='Articulos, intro ...'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_events',
            field=models.CharField(default='', max_length=700, verbose_name='Eventos, intro ...'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_galleries',
            field=models.CharField(default='', max_length=700, verbose_name='Galer\xedas, intro ...'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_photo_1',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo o Frase'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_photo_2',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo o Frase'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_photo_3',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo o Frase'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_photo_4',
            field=models.CharField(default='', max_length=50, verbose_name='Titulo o Frase'),
        ),
        migrations.AddField(
            model_name='ueptemplate',
            name='title_teachers',
            field=models.CharField(default='', max_length=700, verbose_name='Docentes, intro ...'),
        ),
    ]
